name: Generate RSS

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          python -m playwright install --with-deps

      - name: Run generator
        run: python generate.py

      - name: Commit RSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git commit -m "update feed" || echo "no changes"
          git push
